# Generated by Django 4.0.3 on 2022-03-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.TextField()),
                ('marca', models.TextField()),
                ('sustancia', models.TextField()),
                ('forma', models.TextField()),
                ('composicion', models.TextField()),
                ('indicaciones', models.TextField()),
                ('propiedades', models.TextField()),
                ('contraindicaciones', models.TextField()),
                ('restricciones', models.TextField()),
                ('reacciones', models.TextField()),
                ('interacciones', models.TextField()),
                ('hallazgos', models.TextField()),
                ('precauciones', models.TextField()),
                ('dosis', models.TextField()),
                ('manifestaciones', models.TextField()),
                ('presentacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
